application: lol-stats-test
version: 1
runtime: python27
api_version: 1
threadsafe: yes

instance_class: B4_1G
basic_scaling:
  max_instances: 2
  idle_timeout: 10m

handlers:
- url: /js
  static_dir: js

- url: .*
  script: lol_stats.app

libraries:
- name: webapp2
  version: "2.5.2"
